# Learn more: https://shopify.dev/docs/apps/tools/cli/configuration
client_id = "a952b2388664e8e7f7f18e9bd09730e1"
name = "Refund & Return Analytics"
handle = "refund-analytics"
application_url = "https://refund-analytics.fly.dev"
embedded = true

[access_scopes]
scopes = "read_orders"

[auth]
redirect_urls = [
  "https://refund-analytics.fly.dev/auth/callback",
  "https://localhost/auth/callback"
]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["orders/updated"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["refunds/create"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["bulk_operations/finish"]
  uri = "/webhooks"


[pos]
embedded = false
